"""
Web UI Static Files

Serves the interactive dashboard HTML file generated by the presentation layer.
"""
from pathlib import Path


def get_dashboard_html(taxonomy=None) -> str:
    """Generate the complete HTML dashboard file."""
    from .presenter import GraphPresenter
    from ... import Graph

    if taxonomy is None:
        g = Graph()
        g.build_folder_taxonomy()
        taxonomy = g.build_taxonomy()

    # Import from cli.py for now (shared HTML generation)
    from ..cli import generate_taxonomy_html
    return generate_taxonomy_html(taxonomy)